### ISSUE TITLE
Incomplete display in high resolution screen

### ISSUE THREAD

**Issue by Mighty-A** [JolyneFr/QSnake#1]
![image](https://user-images.githubusercontent.com/55054549/102324515-ed25a180-3fbc-11eb-83ee-af5637e49e21.png)
My device:
Surface Book 2 13.5'
resolution: 3000 * 2000 
zoom: 225%
![image](https://user-images.githubusercontent.com/55054549/102324695-29590200-3fbd-11eb-87a2-b6f6f0f007ba.png)

**Comment by JolyneFr** [comment]
Your device is no longer supported.
Please stop using Surface immediately.
